alias disks='sudo lsblk -o NAME,FSTYPE,SIZE,MOUNTPOINT,LABEL'
alias scan='nmap -sP'
alias c='clear && sudo run-parts /etc/update-motd.d/'
alias raid='watch -n 1 cat /proc/mdstat'
alias ports='sudo lsof -i -P -n | grep LISTEN'
alias copy='rsync -a --info=progress2'
alias move='rsync -a --info=progress2 --remove-source-files'
