alias update='sudo apt update && sudo apt upgrade -y'
alias install='sudo apt install'
alias shutdown='sudo shutdown -h now'
alias restart='sudo shutdown -r now'
alias disks='sudo lsblk -o NAME,FSTYPE,SIZE,MOUNTPOINT,LABEL'
alias scan='nmap -sP'
alias c='clear && sudo run-parts /etc/update-motd.d/'
alias raid='watch -n 1 cat /proc/mdstat'
